name: Pradeep Testing custom action
inputs:
  osname:
    required: true
    description: enter osname
    type: string
outputs:
  somedata: ${{ steps.one.outputs.keka }}
    description: return some data
    value: ${{ steps.one.outputs.keka }}
runs:
  using: 'composite'
  steps:
    - name: first step
      id: one
      run: |
        echo "keka=kaka kaka" >> $GITHUB_OUTPUT
        echo "Hello world"
      shell: bash