name: Custo Action Some
author: Pradeep Shetty
description: This is a custom action
inputs:
  osname: 
    required: true
    type: string
    description: enter browser name
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: 'composite'
  steps:
    - id: random-number-generator
      run: |
        echo "random-id=$(echo $RANDOM)" >> $GITHUB_OUTPUT
        echo "Ths os name ${{inputs.osname}}"
      shell: bash