name: My custom action
run-name: new custom action
on: 
    workflow_dispatch:         
        inputs:
            osname: 
                required: true
                type: string
                description: enter browser name

jobs:
    firstjob:
        name: first job
        runs-on: ${{inputs.osname}}
        steps:
            - name: checkout the code
              uses: actions/checkout@v3
            - name: second step
              run: |
                echo "Hello world"
                ls
            - name: i am teisng something
              id: ke
              uses: ./.github/actions/newone
              with:
                osname: ${{inputs.osname}}
            - name: some dad
              run: |
                echo "out is ${{ steps.ke.outputs.somedata }}"
            